[package]
name = "orbitfight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#dynlinks dont work on my machine fmll
bevy = {version = "0.13.1"}
